name: Bug Report
description: File a bug report.
title: "[Bug] "
labels: ["bug"]

body:
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true


  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true

      
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
    validations:
      required: false
      
  - type: textarea
    id: video
    attributes:
      label: Videos
      description: If applicable, add videos to help explain your problem.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: e.g. 55a86b8
    validations:
      required: true

  - type: input
    id: itsrevela
    attributes:
      label: Is this reproducable in itsRevela/LCE-Revelations? (https://github.com/itsRevela/LCE-Revelations)
      description: If this was a "no idea" or similar, it will be rejected.
    validations:
      required: true

  - type: checkboxes
    id: build
    attributes:
      label: Build Type
      options:
        - label: Release
        - label: Debug
    validations:
      required: true

  - type: checkboxes
    id: screenres
    attributes:
      label: Screen Resolution(s)
      options:
        - label: 1080p
        - label: 720p
        - label: 480p
      validations:
        required: true

  - type: checkboxes
    id: operatingsys
    attributes:
      label: Operating System(s)
      options:
        - label: Windows 11
        - label: Windows 10
        - label: Windows 8.1 (not very supported)
        - label: Debian(-based)
        - label: Arch(-based)
        - label: Gentoo(-based)
      validations:
        required: true

  - type: input
    id: launcher
    attributes:
      label: Launcher
      attributes:
        label: Launcher
        placeholder: e.g. Emerald Launcher
      validations:
        required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional context
      description: A clear and concise description of what the bug is.
    validations:
      required: false
